pipeline {
    agent any
    tools{
        maven 'Maven'
        jdk 'JDK'
    }
    stages {
        stage('clone')
        {
            steps {
                echo 'Cloning..'
                git 'https://github.com/edureka-devops/jenkins-demo.git'
            }
        }
        stage('build')
        {
            steps {
                echo 'Building..'
                sh 'mvn -f MavenProject/pom.xml compile package'
            }
        }
        stage('archive')
        {
            steps {
                echo 'Archiving..'
                archiveArtifacts  '**/*.war'
            }
        }
        stage('deploy')
        {
            steps {
                echo 'Deploying..'
                sh "cp MavenProject/multi3/target/*.war 'C://Program Files//Apache Software Foundation//Tomcat 7.0//webapps//'"
            }
        }
        stage('email')
        {
            steps {
                echo 'Emailing..'
                emailext body: 'test', subject: 'test', to: 'germ27germ@hotmail.com'
            }
        }
    }
}
